# open (like in macos)
alias open='xdg-open'

# leet git man
function gitls () {
	if [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
		git ls-files --help

	else
		echo $(git ls-files $@ | awk '{print $4}' | uniq);
	fi
}

# function to quickly connect to a tmux instance in ssh
function ssh_tmux() { ssh -t "$1" "tmux a || tmux"; }

# function to connect to detached tmux session or create a new one
function tmux_connect() {
	DETACHED_SESS=$(tmux list-session -F '#{session_name} #{?session_attached, attached, }' | grep -m 1 -v attached)

	if [ $DETACHED_SESS ]; then
			tmux attach-session -t $DETACHED_SESS
	else
			tmux
	fi
}

# copy to clpboard
alias clip='xclip -sel clip'

# batcat (cat file with syntax)
alias bat='batcat'

alias ls='\ls --color=auto --group-directories-first'
